name: WagerIndex Core Stats Pipeline
on:
  workflow_dispatch: # Run manually only
jobs:
  run-core-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - name: Install Dependencies
        run: pip install pandas requests supabase python-dotenv
      - name: Run Core Stats Pipeline
        run: python run_core_stats.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
