# .github/workflows/daily_run.yml
name: Daily MLB Prediction Job

on:
  schedule:
    # Runs every day at 14:00 UTC (10 AM ET / 7 AM PT)
    - cron: '0 14 * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  run-prediction-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch Current Season Team Stats
        run: python fetch_team_stats.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Fetch Current Season Pitcher Stats
        run: python fetch_pitcher_stats.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          
      - name: Fetch Today's Games
        run: python fetch_games.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Run Prediction Model
        run: python run_model.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
