name: Daily Fetch + Model Run

on:
  schedule:
    - cron: "0 12 * * *" # Runs every day at 12:00 UTC (7 AM Central)
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  run-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install supabase pybaseball python-dotenv

      - name: Run fetch_games.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python fetch_games.py

      - name: Run fetch_game_results.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python fetch_game_results.py

      - name: Run fetch_pitcher_stats.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python fetch_pitcher_stats.py

      - name: Run fetch_team_stats.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python fetch_team_stats.py

      - name: Run run_model.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python run_model.py
